# Generated by Django 3.1.5 on 2021-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openstreetmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myosm',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myosm',
            name='center',
            field=models.CharField(default='Onlineformapro', max_length=100),
        ),
        migrations.AddField(
            model_name='myosm',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myosm',
            name='image',
            field=models.ImageField(default='onlineformapro.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='myosm',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
