# Generated by Django 3.1.5 on 2021-01-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openstreetmap', '0002_auto_20210126_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myosm',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myosm',
            name='center',
        ),
        migrations.RemoveField(
            model_name='myosm',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myosm',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myosm',
            name='zipcode',
        ),
    ]
