# Generated by Django 3.1.5 on 2021-02-02 14:07

from django.db import migrations
import osm_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openstreetmap', '0009_auto_20210202_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myosm',
            name='location',
            field=osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon', verbose_name='Location (address, zipcode city)'),
        ),
    ]
