# Generated by Django 3.1.6 on 2021-02-04 08:24

from django.db import migrations, models
import django.db.models.deletion
import osm_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openstreetmap', '0010_auto_20210202_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openstreetmap.myosm'),
        ),
        migrations.AlterField(
            model_name='myosm',
            name='location',
            field=osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon'),
        ),
    ]
